version: '3'
services:
  broker:
    image: eclipse-mosquitto:2.0.20
    restart: on-failure
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt-messaging

  db:
    image: influxdb:1.11.8
    restart: on-failure
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - type: bind
        source: ${SCD_DVP}/influxdb
        target: /var/lib/influxdb
    networks:
      - visualization
      - db-update

  adaptor:
    image: mqtt-to-db-adaptor:latest
    restart: on-failure
    depends_on:
      - db
      - broker
    networks:
      - mqtt-messaging
      - db-update
  
  dashboard:
    image: grafana/grafana:latest
    restart: on-failure
    ports:
      - '80:80'
    depends_on:
      - db
    networks:
      - visualization


# volumes:
#   db_data:
#     driver: local
#     driver_opts:
#       type: none
#       device: ${SCD_DVP}
#       o: bind

networks:
  mqtt-messaging:
  visualization:
  db-update:
